### ISSUE TITLE
Compatibility with mdx

### ISSUE THREAD

**Issue by dominiwe** [wooorm/remark-comment-config#10]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Currently, something like this will not work when using MDX (with e.g. [mdx-bundler](https://github.com/kentcdodds/mdx-bundler)):

```html
<!--remark bullet="+"-->
```

This is because MDX v2 doesn't support html comments.

### Solution

 Instead, it supports comments like this:

```js
{/* remark bullet="+" */}
```

### Alternatives

There is also the [remark-comment](https://www.npmjs.com/package/remark-comment) plugin which parses html comments into a different node type. So perhaps it would be cool if it would be configurable for this plugin.

**Comment by wooorm** [comment]
MDX 2 comments are already supported, see the lower-level tool that is used: https://github.com/syntax-tree/mdast-comment-marker.

If it doesn’t work for you, my likely guess is that a) mdx-bundler is outdated, or b) your dependencies are outdated. 

Also note that this has nothing to do with `remark-comment`, which should not be needed.

**Comment by dominiwe** [comment]
You're right... I got very confused there. I was parsing mdx with remark and then used rehype right after meaning that I didn't see what the plugin even does (I just looked at the generated html after).
